### ISSUE TITLE
Daily Checkboxes get unchecked every second

### ISSUE THREAD

**Issue by jonathan-pe** [dailyark/dailyark.github.io#1]
Every time I check a daily checkbox, it gets unchecked whenever the timer changes.

![image](https://user-images.githubusercontent.com/11398260/153973177-5465ef0d-09b3-4f98-be1b-86dcd02a0903.png)

It looks like when the daily timestamp gets generated, it comes out with a timestamp larger than the current time (or so I think by comparing it to the weekly timestamp [weeklies works fine]). Hope this helps :)

**Comment by majorcyto** [comment]
Can confirm I have the same issue with the checkbox unchecking itself on Daily.

**Comment by KuwuroUsagi** [comment]
+1 checked boxes uncheck themselves immediately

Using Version 98.0.4758.102 (Official Build) (64-bit) of Google Chrome

**Comment by dailyark** [comment]
Fixed in #4
