### ISSUE TITLE
Possible Bug: Weekly tasks reset on daily reset timer

### ISSUE THREAD

**Issue by Khamulus** [dailyark/dailyark.github.io#13]
Weekly Tasks (Roster & Character specific) always reset with daily reset (Using Firefox, didn't try other browsers yet)

(Uploaded the script to my own webhost)

**Comment by dailyark** [comment]
I have checked locally on my test environment, and it seems to be working just fine.

I will monitor it for Friday, as tomorrow is the actual weekly reset.

**Comment by dailyark** [comment]
Weekly tasks didn't reset on the live version either. Closing.
