### ISSUE TITLE
Possibly wrong daily reset timer?

### ISSUE THREAD

**Issue by btlm** [dailyark/dailyark.github.io#19]
Hello,

daily reset timer seems to be 1 hour behind actual time (so do weekly timer). Not sure if it is a problem with time zones or something else. My timezone is CET and reset occurs at 11 CET (currently is 11:25 CET).
![image](https://user-images.githubusercontent.com/25756904/158055209-067602ec-aa9a-4ff8-abf3-6319bfcfe7e7.png)

**Comment by dailyark** [comment]
Fixed 2 minutes ago, ctrl + F5
