### ISSUE TITLE
Feature Request: Being able to resize and relocate the sections as well as being able to list them horizontally.

### ISSUE THREAD

**Issue by Just2good** [dailyark/dailyark.github.io#3]
I use the Force 21:9 option in game and it adds black bars to the top and bottom of my screen. I also have a program that copies a window and overlays it on top of any of my screens. Would be nice to make the checkboxes+title box customizable so that I can overlay them on top of the black bars.

Image attached as an example. This is definitely a specific request and understandable if this doesn't make it in/super low prio.
![LOSTARK_eptnjrbHVr](https://user-images.githubusercontent.com/13886887/154003530-865c23c7-b95e-4412-a548-382ee1b3ff65.jpg)

**Comment by dailyark** [comment]
Added relocate in the latest release. Is currently deploying.
