### ISSUE TITLE
FR: Entry for Daily Stronghold missions?

### ISSUE THREAD

**Issue by Ebsy** [dailyark/dailyark.github.io#8]
Love the app. 
Would it be worth adding an entry for daily Stronghold missions?

**Comment by lorddusk** [comment]
Daily Stronghold mission?

If you can give me a link to more information, I will add it.

**Comment by Ebsy** [comment]
Sure. I couldn't find anything specific on Papunika but [here's a quick reference](https://www.thegamer.com/lost-ark-daily-checklist-endgame-content/#:~:text=Check%20your%20Stronghold%2C%20upgrade%20your%20Stronghold%2C%20and%20send%20sailors%20out%20on%20Dispatch%20missions.)

Basically, you should be doing at least one of the Stronghold Dispatch missions per day (plus research etc. earning XP towards leveling your Stronghold)

**Comment by dailyark** [comment]
So it's not an actual Daily? Then I don't think I will add it, as everything on the checklist currently is a "once per day/week" lockout

**Comment by Ebsy** [comment]
ah fair enough. They are reset once a day but yes, they're not a 'true' daily.
Thanks again for the app 👍
