### ISSUE TITLE
Feature Request: Rest Bonus stacks

### ISSUE THREAD

**Issue by Sinpls** [dailyark/dailyark.github.io#9]
Hi, would it be possible to add rest bonuses to characters depending on whether the daily content has been done on said characters? Would be great to see it so I can never overcap on rest bonus.

**Comment by dailyark** [comment]
I mean, I could add extra checkboxes, but you would need to do it manually... And that is kinda dumb.

**Comment by dailyark** [comment]
Out of scope for this project.
